### ISSUE TITLE
Node service container reports an error that npm doesn't exist

### ISSUE THREAD

**Issue by michaellwest** [sitecorelabs/XmCloudPreview#2]
After running `.\up.ps1` I noticed an issue with the health of the node container. The logging output reported npm as not a known command. Further inspection revealed that the folder **C:\node** was missing all permissions on the filesystem.

Adding `RUN icacls.exe c:\node /grant Users:(F) /t` before changing to **ContainerUser** appears to correct the issue. Not sure if this issue is related to the Docker 4.7.1 update but it did help me move forward.

**Comment by iamandycohen** [comment]
Fixed
